
modLoader="javafml"
loaderVersion="[46,)"
license="Pineapple"
[[mods]]
modId="coffee_delight"
version="${file.jarVersion}"
displayName="Coffee Delight"
logoFile="CoffeeDelight.png"
credits="Someoneice"
authors="Someoneice"
description='''
'''
[[dependencies.coffee_delight]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.coffee_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"